info:
  contact: {}
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Authentifie un utilisateur avec email et mot de passe
      parameters:
      - description: Identifiants de connexion
        in: body
        name: credentials
        required: true
        schema:
          properties:
            email:
              type: string
            password:
              type: string
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: Connexion OK ou JWT
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Identifiants incorrects
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Se connecter
      tags:
      - Auth
  /register:
    post:
      consumes:
      - application/json
      description: Crée un nouvel utilisateur avec email, nom, mot de passe et solde
        par défaut
      parameters:
      - description: Utilisateur à enregistrer
        in: body
        name: user
        required: true
        schema:
          properties:
            email:
              type: string
            name:
              type: string
            password:
              type: string
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: Utilisateur créé
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Entrée invalide
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Email déjà utilisé
          schema:
            additionalProperties:
              type: string
            type: object
      summary: S'inscrire
      tags:
      - Auth
swagger: "2.0"
