{
  "preset": "angular",
  "changelog": {
    "template": "# Changelog\n\n{{range .Versions}}{{if .Tag.Previous}}## {{if .Tag.Name}}{{.Tag.Name}}{{else}}{{.Tag.Previous.Name}}{{end}} ({{.Tag.Date.Format \"2006-01-02\"}})\n{{range .CommitGroups}}### {{.Title}}\n{{range .Commits}}* {{if .Scope}}**{{.Scope}}:** {{end}}{{.Subject}}{{if .Body}} - {{.Body}}{{end}}{{end}}\n{{end}}{{if .RevertCommits}}### Reverts\n{{range .RevertCommits}}* {{.Revert.Header}}{{end}}\n{{end}}{{end}}{{end}}"
  },
  "commitsParser": {
    "headerPattern": "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$",
    "breakingPattern": "^BREAKING CHANGE: ",
    "headerCorrespondence": [
      "type",
      "scope",
      "subject"
    ]
  },
  "releaseRules": [
    { "type": "feat", "release": "minor" },
    { "type": "fix", "release": "patch" },
    { "type": "docs", "release": "patch" },
    { "type": "style", "release": "patch" },
    { "type": "refactor", "release": "patch" },
    { "type": "perf", "release": "patch" },
    { "type": "test", "release": "patch" },
    { "type": "ci", "release": "patch" },
    { "type": "chore", "release": "patch" },
    { "scope": "breaking", "release": "major" }
  ]
}
